### ISSUE TITLE
Error running docker..

### ISSUE THREAD

**Issue by waynebrantley** [dzwicker/docker-youtrack#3]
Brand new ubuntu install, new docker install, all updates applied
Gives error see picture.   

![image](https://cloud.githubusercontent.com/assets/157082/10118933/1a2ba3b2-6455-11e5-8802-1d89814a4cdd.png)

**Comment by waynebrantley** [comment]
think https://github.com/dzwicker/docker-youtrack/pull/4 fixes it

**Comment by dzwicker** [comment]
The error is produced by java. So the youtrack.jar is started/found. 

I know this error. Try to chown the /var/lib/youtrack folder on the host system to the youtrack user (uid 2000). Or any other user which has the uid 2000. If it doesn't exist create one. The name is not important. It is matched by the uid.

Please let me know if it fix the problem. Then i will adjust the docs. I think i haven't mentioned this.

**Comment by waynebrantley** [comment]
See my pull request....it was your wget downloading it as one filename and your sh script running it as another!

**Comment by dzwicker** [comment]
I saw your pull request. I create a sysmlink just after downloading the jar. ```ln -s /usr/local/youtrack/youtrack-$YOUTRACK_VERSION.jar /usr/local/youtrack/youtrack.jar```. 

Have you tried your pull request with mounting a volume to /var/lib/youtrack. Without using this volume the error is gone. Even in the original version.

**Comment by waynebrantley** [comment]
sysmlink - I did not notice that!   (why not just copy it as the correct filename to start with or use the env variable to start with, one less command)?

I did not try my pull request.  I just executed the commands in the script manually and they worked, assuming I used the right name on the jar file.     

My command above in the screen shot I am mounting the volume.  Then you say error is going without using the volume.  I am confused at this point?

**Comment by dzwicker** [comment]
I believe ist just a permission problem. The container executes all commands as the youtrack user. Which has no permission to write to the mounted volume. Without the volume the directory inside the container file system is used. And the Dockerfile sets the permissions for this folder.

**Comment by waynebrantley** [comment]
Yep, it does work without volume.  Also on your directions page - the directions under "oh nice..." are not quite right now...
You have this:
```docker run -t -i -p 127.0.0.1:8080:8080 dzwicker/docker-youtrack```
and it should be
```docker run -t -i -e "YOUTRACK_BASE_URL=x" -p 127.0.0.1:8080:8080 dzwicker/docker-youtrack```
