### ISSUE TITLE
SSL using nginx-proxy

### ISSUE THREAD

**Issue by huglester** [dzwicker/docker-youtrack#8]
Hello

I have tried using  https://github.com/jwilder/nginx-proxy but with SSL with no luck

```bash
/usr/bin/docker run -t \
	--name youtrack \
	-v /data/youtrack/data/:/opt/youtrack/data/ \
	-v /data/youtrack/backup/:/opt/youtrack/backup/ \
	-e VIRTUAL_HOST=sub.domain.com \
	-e VIRTUAL_PROTO=https \
	uniplug/youtrack
```

but It does not work really.. not sure where to look at. maybe you have some ideas?

**Comment by waynebrantley** [comment]
This is what we use.
https://github.com/miniter/nginx_yt_compose
